//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignPaper
    {
        public int PaperId { get; set; }
        public string ReviewerId { get; set; }
        public int Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Paper Paper { get; set; }
    }
}
