//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paper()
        {
            this.AssignPapers = new HashSet<AssignPaper>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Topic { get; set; }
        public Nullable<int> No__of_review { get; set; }
        public string author_id { get; set; }
        public Nullable<int> conference_id { get; set; }
        public string final { get; set; }
        public string status { get; set; }
        public string Content { get; set; }
        public string Text { get; set; }
        public int Value { get; set; }
        public List<Paper> expertList { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignPaper> AssignPapers { get; set; }
        public virtual Conference Conference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
